### ISSUE TITLE
Can it be used outdoor ?

### ISSUE THREAD

**Issue by txaj** [Miceuz/i2c-moisture-sensor#1]
Or even buried 5-6 cm underground ? 

(I'm sorry to open an issue to ask a question but I couldn't find any way to contact you without registering on tindie)

**Comment by Miceuz** [comment]
You would want to  cover in additional protection the place where cable 
is soldered to the sensor, some people are putting a tube over the 
electronics and pouring epoxy or silicone into it.

Regarding burying it underground - you would have to test this yourself 
;) The answer would be "probabaly" after you pot it with above method.

On 06/28/2015 08:08 PM, txaj wrote:

> Or even buried 5-6 cm underground ?
> 
> (I'm sorry to open an issue to ask a question but I couldn't find any
> way to contact you without registering on tindie)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Miceuz/i2c-moisture-sensor/issues/1.
> 
> [ok]

## 

mic.

**Comment by dedekcz** [comment]
@Miceuz Nice project, Do You have any recommendation which epoxy is right one? is there any request for conductivity properties?

**Comment by Miceuz** [comment]
You will get different reading with different kind of epoxy, but in general it does not matter al long as you calibrate after potting, make sure it's just non-conductive one, having no metal inside.
