### ISSUE TITLE
Trigger external reset

### ISSUE THREAD

**Issue by pilotak** [Miceuz/i2c-moisture-sensor#10]
Hi I'm using this sensor with with ESP8266 and it works perfectly @8MHz. I'm not using termistor and LED. Is there any chance you could provide me with a code to wake up on FALLING edge on PCINT9 and then trigger 10ms LOW on PA3 and then go to sleep again? I would use it to trigger reset on ESP and wake up when charger got connected.

Thank you
Pavel

**Comment by Miceuz** [comment]
Hi,

Frankly, the code is there, go on and use it as you like, I don't provide support at this level, sorry.

**Comment by pilotak** [comment]
That's fine. And if I pay, are interested?

Dne 16. 8. 2016 6:32 odpoledne napsal uživatel "Albertas Mickėnas" <
notifications@github.com>:
