### ISSUE TITLE
low power usage

### ISSUE THREAD

**Issue by parallelpilgrim** [Miceuz/i2c-moisture-sensor#12]
Is there any way you are aware of to get power usage while sleeping under 1.1mA?

I've been looking at some of the sleep code for hints but was wondering if anything like this was planned.

Ideally under 1mA would be ideal for sleep mode consumption. Additionally I only care about moisture readings.

thanks!

**Comment by Miceuz** [comment]
Hi,

Yes, there is a sleep instruction you can issue via I2C. Then thermistor circuit dominates the power consumption - 20k @ 5V makes it 250uA, 20k @ 3.3V - 165uA. There is no way around this currently, but I will fix it in the next revision of the sensor. My experiments show that I can get as low as 2uA in deep sleep mode. But anyway, It will be well under 1mA in the current revision.
