### ISSUE TITLE
improve sensitvity

### ISSUE THREAD

**Issue by mindforger** [Miceuz/i2c-moisture-sensor#15]
one thing in advance, i am not profesional in things like electronics but i talked to a co-worker beeing professional and asked him if i could probably get better sensitvity on this

he told me you could mirror the capacitor layout on both sides of the PCB and connect the planes with a few vias, this increases the overall capacity coupling over the surface and greatly reduces the coupling through the PCB material itself, resulting probably in an overall capacity loss but a great improvement on capacity change through the surface field

**Comment by Miceuz** [comment]
Thanks for the tip! I am not sure if there really is any need for more sensitivity for now.
