### ISSUE TITLE
HW question: Why is there space between capacity and electronics

### ISSUE THREAD

**Issue by 2ni** [Miceuz/i2c-moisture-sensor#24]
Hi
Sorry to bother you... I was just wondering if the sensor needs to be that long. Couldn't it be shortened in total by bringinge the logic and attiny closer to the capacity pad? What is the reason for that space (the length of SENSOR_TRACK on the pcb)?

**Comment by Miceuz** [comment]
It's to put electronics further away from soil, no other technical reason.
