### ISSUE TITLE
Instructions for upgrading from 2.4 to 2.7 firmware?

### ISSUE THREAD

**Issue by akutruff** [Miceuz/i2c-moisture-sensor#28]
Hi,

I had the sensor running with the Arduino I2C example on firmware 2.4.  (I don't believe 2.4 supported all the registers but it was generally working.) I verified I was getting valid values for capacitance.   

I made an attempt to flash to the latest firmware against latest source in this repository.  

In a Ubuntu VM, I did:

`
make hex 
`

I then copied the main.hex out to windows to do the flash.  (VM's do not like USB programmers apparently.)

I ran:

```
avrdude.exe -c usbtiny -p t44 -U flash:w:main.hex:i -V
avrdude.exe -c usbtiny -p t44 -U hfuse:w:0xDF:m -U lfuse:w:0xAE:m efuse:w:0xF5:m -B 40.96
```
I took those values from the makefile.

I noticed there's a "programmer" folder under src that I did not utilize which makes me believe I missed a step.  Would someone be so kind as to provide guidance? Thanks!

**Comment by Miceuz** [comment]
Hi, 

You are using -p t44 which suggests you are trying to flash the device based on attiny44 which is really old version, only Chirp plant watering alarm use those nowdays. This firmware is written for attiny441.
