### ISSUE TITLE
Sleep mode: Rak module require datas

### ISSUE THREAD

**Issue by vrenaville** [Miceuz/i2c-moisture-sensor#36]
Hello,

With RAK811 module, It support only writing data to registry , not directly on the devise (they told me it's not standard to write directly on the devise)
Do you know if I can write data on the register to set enforce sensor going to sleep ?

Kind regards,

Vincent

**Comment by Miceuz** [comment]
Hi @vrenaville what standard are they refering to? I am not aware of this limitation. 

No way around it from what I have seen.

One hack you can try is write 0x08 into register 0x08. If I am right, the sensor will go to sleep and come back from it immediately after receving 0x08 and will interpret that as sleep command and go to sleep again.

**Comment by vrenaville** [comment]
I have tried to write 0x08 byte on register 0x08, it's accepted, but after the I2C bus and sensor are completely stuck. 
Need to cold restart of RAK and Sensor.

Anyway it's more a Rak issue than from your sensor, but let's wait they improve their tools
