### ISSUE TITLE
Mosfet instead of Q2 and Q3 bipolar ?

### ISSUE THREAD

**Issue by pit34** [Miceuz/i2c-moisture-sensor#39]
Hello,

I ask myself why does Q2 and Q3 are bipolar tranistor and not mosfet ?
There is an explanation of operation here :
https://wemakethings.net/2012/09/26/capacitance_measurement/
But not why bipolar instead of mosfet to discharge the capacitor.

Thanks

**Comment by kriskeillor** [comment]
Just a guess from me, but BJTs are cheaper and they do the same thing. That could be the reason.

**Comment by Miceuz** [comment]
Err, I don't remember exactly, but I think BJTs I had in my bin were faster to switch than mosfets I had. But in general I had to scrap the idea of discharging as it creates a lot of complication (switching transistor really fast is not simple) and does not give a lot of pros.
