### ISSUE TITLE
Include data format in register address

### ISSUE THREAD

**Issue by kriskeillor** [Miceuz/i2c-moisture-sensor#40]
The [I2C register map](https://github.com/Miceuz/i2c-moisture-sensor#i2c-protocol) does not define the data format, and the listed examples use different ways of calculating them.

E.g., the [example by Daniel Tamm and Jasper Wallace](https://github.com/Miceuz/i2c-moisture-sensor#raspberry-pi-examples) simply prints the raw registers as Temp (C or F?), Moisture (Relative Humidity?), and Light (Lux?). Meanwhile, the example from _krikk_ (second code block following above anchor link) treats light and moisture as raw values, while temp is divided by ten.

All in all, the data format and unit of the sensor readings needs to be provided in the I2C register map (or somewhere else).

**Comment by dj-bauer** [comment]
He provides the interpretation of the sensor values on his tindie-page
https://www.tindie.com/products/miceuz/i2c-soil-moisture-sensor/

**Comment by Miceuz** [comment]
Thanks for pointing this out @kriskeillor
